# Generated by Django 3.2.13 on 2022-05-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='output_images_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
